### ISSUE TITLE
getEventsAtBlockHeightRange does not indicate if some blocks were past the latest block height

### ISSUE THREAD

**Issue by chriswayoub** [onflow/sdks#13]
### Problem

When calling `getEventsAtBlockHeightRange`, if the latest block height is 1000 and you request 999 - 1010, the call returns successfully and you have no indication that blocks 1001 - 1010 were not actually available. This is an issue when you are continuously querying the latest block(s) for events. On certain requests, the latest blocks may not be available (I'm assuming this depends on which access node you happen to to hit). You can't be sure if the blocks were not available yet, or if there were no events in those blocks.

The Go SDK handles this by returning an array of every block that was queried along with a nested array of the events for that block. If you request something past the latest block height, the blocks that are not available will not be included in the results. So in the example above, you would only receive results for blocks 999 - 1000, and 1001-1010 would be missing from the results (which is what I would expect).

I'm not sure what the solution for this is with the current JS `getEventsAtBlockHeightRange` if you want to maintain backward compatibility, since it is just an array of all events (they are not grouped in the same way that the Go SDK results are).

### Steps to Reproduce

```javascript
const latestBlock = await sdk.send(
      await sdk.build([
        sdk.getBlock(true),
      ]), {
        node: this.accessNode,
      }).then(sdk.decode)

const events = sdk.getEventsAtBlockHeightRange('testEvent', latestBlock.height, latestBlock.height + 10),

// at this point, events will contain any events of 'testEvent' type for the latest block
// there is no indication that the other 9 blocks that were queried were not available.
```

I think this may be related to issue onflow/fcl-js#583

**Comment by justinbarry** [comment]
Unsure if this belongs here but if it belongs anywhere, it is here.
